### ISSUE TITLE
Add validation for a list of events

### ISSUE THREAD

**Issue by kristinapathak** [xmidt-org/interpreter#9]
This will allow us to know if the last boot time provided by a list of events is considered valid.  Some examples of `eventsValidator`s we might want:
1. an events validator that makes sure the last disconnect from the xmidt cluster is due to a reboot (rather than a rehash or network issue).  This would mean that the most recent disconnect+reconnect has a new boot time.
1. an events validator that makes sure the most recent reboot (new boot time) has all the RDK events in the correct order: `reboot-pending`, `offline`, `online`, `operational`, `fully-manageable`.

Unlike the event validator, where we can put multiple in a slice and run them all, in this case we will probably only want to run one `eventsValidator` at a time, unless we want to iterate through the list of events multiple times.  I am working under the assumption that we want to do this as few times as possible.  Using an `eventsValidator` and an event finder in the same struct already means iterating through the list twice.  But keeping both separate helps to modularize the code and separate concerns.

Some remaining questions:
- Should the second events validator also make sure that the most recent reboot found is also the most recent disconnect? (I think yes)

**Comment by kristinaspring** [comment]
After discussing with @j-mai, we realized another change that would make a lot of sense is moving the `fatalValidator` parameter from the finder interface into this `eventValidators` one.

**Comment by j-mai** [comment]
Additional checks that we should add:
1. Metadata consistency: `metadata/hw-mac`, `metadata/hw-manufacturer`, `metadata/hw-model`, `metadata/hw-serial-number`, `metadata/partner-id` should be the same among the events in the list.
2. Transaction_uuid between events in the list are different
3. An online and offline event exists in the list
4. Among events with the same boot-time, the following are the same: `metadata/fw-name`, `metadata/hw-last-reboot-reason`, `metadata/webpa-protocol`
